# Generated by Django 5.2.4 on 2025-09-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pdfverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='main.semester', verbose_name='Semestr'),
        ),
    ]
