# Generated by Django 5.2.4 on 2025-09-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='main.semester', verbose_name='Semestr'),
        ),
    ]
