# Generated by Django 5.2.4 on 2025-09-26 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_test_video_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='intro_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_videos', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intro_videos', to='main.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_videos', to='main.subject')),
            ],
            options={
                'verbose_name': 'Intro video',
                'verbose_name_plural': 'Intro videolar',
                'constraints': [models.UniqueConstraint(fields=('subject', 'semester', 'created_by'), name='uniq_intro_video_per_teacher_subj_sem')],
            },
        ),
    ]
