# Generated by Django 5.2.4 on 2025-09-26 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_introvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name='O‘qituvchi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.group', verbose_name='Guruh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['-created_at'],
                'unique_together': {('subject', 'group', 'title', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='TopicIntroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Video URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='topic_videos/', verbose_name='Video fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intro_video', to='main.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Mavzu intro video',
                'verbose_name_plural': 'Mavzu intro videolar',
            },
        ),
        migrations.CreateModel(
            name='TopicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='topic_questions/', verbose_name='Rasm')),
                ('question_type', models.CharField(choices=[('single', 'Bitta to‘g‘ri javob'), ('multi', 'Ko‘p to‘g‘ri javob')], default='single', max_length=10, verbose_name='Savol turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_questions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Mavzu savoli',
                'verbose_name_plural': 'Mavzu savollari',
            },
        ),
        migrations.CreateModel(
            name='TopicAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name='To‘g‘ri javobmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.topicquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Mavzu javob varianti',
                'verbose_name_plural': 'Mavzu javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='TopicStudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('total_score', models.FloatField(default=0, verbose_name='Ball')),
                ('completed', models.BooleanField(default=False, verbose_name='Tugadimi')),
                ('randomized_question_ids', models.JSONField(blank=True, default=list, verbose_name='Random tartib savollar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_student_tests', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Mavzu talaba testi',
                'verbose_name_plural': 'Mavzu talaba testlari',
            },
        ),
        migrations.CreateModel(
            name='TopicStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='To‘g‘rimi')),
                ('score', models.FloatField(default=0, verbose_name='Ball')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_student_answers', to='main.topicquestion', verbose_name='Savol')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='chosen_in', to='main.topicansweroption', verbose_name='Tanlangan variantlar')),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.topicstudenttest', verbose_name='Talaba testi')),
            ],
            options={
                'verbose_name': 'Mavzu talaba javobi',
                'verbose_name_plural': 'Mavzu talaba javoblari',
            },
        ),
        migrations.CreateModel(
            name='TopicTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('question_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('total_score', models.PositiveIntegerField(verbose_name='Umumiy ball')),
                ('duration', models.DurationField(verbose_name='Test muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Faol')),
                ('question_ids', models.JSONField(blank=True, default=list, verbose_name='Tanlangan savollar ID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_tests', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='main.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Mavzu testi',
                'verbose_name_plural': 'Mavzu testlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='topicstudenttest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_runs', to='main.topictest', verbose_name='Test'),
        ),
        migrations.DeleteModel(
            name='IntroVideo',
        ),
        migrations.AddConstraint(
            model_name='topicstudenttest',
            constraint=models.UniqueConstraint(fields=('student', 'test'), name='unique_topic_student_test_once'),
        ),
    ]
