# Generated by Django 5.2.4 on 2025-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_topic_topicintrovideo_topicquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictest',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='topic_tests_multi', to='main.group', verbose_name='Qo‘shimcha guruhlar'),
        ),
    ]
