# Generated by Django 5.2.4 on 2025-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_topic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictest',
            name='question_block_size',
            field=models.PositiveIntegerField(default=0, help_text='>0 bo‘lsa savollar shu hajmdagi bloklarda alohida aralashtiriladi', verbose_name='Blok hajmi (0=oddiy)'),
        ),
        migrations.AddField(
            model_name='topictest',
            name='shuffle_options',
            field=models.BooleanField(default=True, verbose_name='Variantlar aralashtirilsinmi'),
        ),
        migrations.AddField(
            model_name='topictest',
            name='shuffle_questions',
            field=models.BooleanField(default=True, verbose_name='Savollar aralashtirilsinmi'),
        ),
    ]
