# Generated by Django 5.2.4 on 2025-10-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_question_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='multi_tests', to='main.group', verbose_name='Biriktirilgan guruhlar'),
        ),
    ]
