# Generated by Django 5.2.4 on 2025-10-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_test_updated_at_test_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bulim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='main.bulim', verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='question',
            name='kafedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='main.kafedra', verbose_name='Kafedra'),
        ),
    ]
