# Generated by Django 5.2.4 on 2025-10-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_question_bulim_question_kafedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bulimlar',
            field=models.ManyToManyField(blank=True, related_name='multi_tests', to='main.bulim', verbose_name="Biriktirilgan bo'limlar"),
        ),
        migrations.AddField(
            model_name='test',
            name='kafedralar',
            field=models.ManyToManyField(blank=True, related_name='multi_tests', to='main.kafedra', verbose_name='Biriktirilgan kafedralar'),
        ),
    ]
