# Generated by Django 5.2.4 on 2025-10-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_test_bulimlar_test_kafedralar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Otasining ismi'),
        ),
    ]
