# Generated by Django 5.2.4 on 2025-10-23 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pass_percent',
            field=models.PositiveIntegerField(default=60, help_text="Talabaning foiz natijasi shu qiymatdan >= bo'lsa o'tgan hisoblanadi", verbose_name="O'tish foizi"),
        ),
        migrations.CreateModel(
            name='Dalolatnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name="O'tkazish joyi")),
                ('reason', models.TextField(verbose_name='Qoida buzilishi sababi')),
                ('observers', models.TextField(blank=True, null=True, verbose_name='Nazoratchilar (FIO, vergul bilan)')),
                ('file', models.FileField(upload_to='dalolatnomalar/', verbose_name='PDF fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dalolatnomalar', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dalolatnomalar', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('student_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalolatnomalar', to='main.studenttest', verbose_name='Talaba testi')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dalolatnomalar', to='main.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Dalolatnoma',
                'verbose_name_plural': 'Dalolatnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
